// Type definitions for papaparse
// Project: https://www.papaparse.com/
// Definitions by: papaparse <https://www.papaparse.com/>
// Definitions:
// TypeScript Version: 5.9
// This file was auto-generated by the TypeScript definition generator for papaparse.
// src/types/papaparse.d.ts

declare module "papaparse";
